add back door announce
tier4/AutowareSignage pull request #19
Opened 2022-02-08 01:02 UTC by tkhmy

Signed-off-by: tkhmy <tkh.my.p@gmail.com>

2022-02-08 08:13 UTC, yabuta commented on src/signage/src/signage/announce_controller.py
> +        elif door_status in [0, 2, 5]:
_pre_door_announce_statusはすべての場合で更新しないと連続してstatus = 3が来た場合などで発話が繰り返されてしまうと思います

ドア開閉状態はoperator modeと同じように定期的に配信されるトピックになると思います

2022-02-08 09:33 UTC, tkhmy commented on src/signage/src/signage/announce_controller.py
> +        elif door_status in [0, 2, 5]:
door status は定期的に配信されるトピック、 door status は更新したの時だけ発話したいの意味ですか？
現在は_pre_door_announce_status と door_status違うと時だけ、発話すると思います。

2022-02-08 09:33 UTC, tkhmy commented on src/signage/src/signage/announce_controller.py
> +        elif door_status in [0, 2, 5]:
この感じに整理しました。　
https://github.com/tier4/AutowareSignage/pull/19/commits/8e107c85b583d9b08d53607ffd7fcc7e12a3f683#diff-e1cb7e4e8d86928337d396d057939723b027cb1795bc0261794be9efe85b9a0eR159

2022-02-09 00:45 UTC, yabuta commented on src/signage/src/signage/announce_controller.py
> +        elif door_status in [0, 2, 5]:
ありがとうございます。自分の環境で試したときdoor status = 3を1Hzで送るとsubするごとに発話してしまっていました
この修正で大丈夫だと思いますが確認するのでちょっと待ってください

2022-02-09 01:22 UTC, yabuta requested changes

2022-02-09 01:22 UTC, yabuta commented on src/signage/src/signage/route_handler.py
> +        if self._pre_door_announce_status == door_status:
サイネージが起動したときドアが開閉中（door status=3,4）だと発話を行いますがこの場合は発話しないほうが自然だと思います（ドア開閉の途中で発話してもバグっぽく感じる気がします）

起動時や_pre_door_announce_statusがUNKNOWNのときは次のdoor statusが何であれ発話しないようにするのが良いのではと思います

2022-02-09 01:22 UTC, yabuta commented on src/signage/src/signage/announce_controller.py
> +        elif door_status in [0, 2, 5]:
こちらはOKだと思います

2022-02-09 05:41 UTC, tkhmy commented on src/signage/src/signage/route_handler.py
> +        if self._pre_door_announce_status == door_status:
> サイネージが起動したときドアが開閉中（door status=3,4）だと発話を行いますがこの場合は発話しないほうが自然だと思います（ドア開閉の途中で発話してもバグっぽく感じる気がします）

もし開閉前、サイネージはそのタイミングで発話するは自然ですが、
現在はいつドアが開閉は取らないので、開閉中で発話する方が自然です。

ドアが開閉完了後で、発話すると逆に変になります。
ドアが開完了 -> ドアが開きます。ご注意ください
ドアが閉完了 -> ドアが閉まります。ご注意ください

> 起動時や_pre_door_announce_statusがUNKNOWNのときは次のdoor statusが何であれ発話しないようにするのが良いのではと思います
起動の時、ドアは`DOOR_OPENED` か`DOOR_CLOSED` の状態なので、発話しないと思います。

2022-02-09 08:17 UTC, yabuta approved these changes

2022-02-10 04:25 UTC, tkhmy commented
Merge this, After this https://github.com/tier4/tier4_ad_api_adaptor/pull/16 is merged

2022-02-14 01:36 UTC, yabuta commented
@tkhmy 今日PS１で平川さんがドアを使えるようにするらしいのでできれば今日中にマージして明日確認してみましょう

2022-02-14 02:19 UTC, merged