Feat/slow stop
tier4/AutowareSignage pull request #77
Opened 2023-09-01 06:10 UTC by tkhmy

## Related Issue(required)

## Description(required)
- add slow stop view

## Review Procedure(required)

## Related PR(optional)

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [commit-guidelines][commit-guidelines]
- [ ] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write release notes

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

2023-09-08 02:20 UTC, yabuta requested changes

2023-09-08 02:20 UTC, yabuta commented on src/signage/src/signage/route_handler.py
> +            in_emergency = self._autoware.information.mrm_behavior == MrmState.EMERGENCY_STOP
すみません、意図を伝えきれてなかったですが減速中は「減速します」という表示はそのままにしてもらってもいいでしょうか？

「減速します」と表示する条件
```
self._autoware.information.mrm_behavior == MrmState.COMFORTABLE_STOP
and self._autoware.information.motion_state == MotionState.MOVING
```
「安全確認のため停車中です」と表示する条件
```
self._autoware.information.mrm_behavior == MrmState.COMFORTABLE_STOP
and self._autoware.information.motion_state == MotionState.STOPPED
```

2023-09-08 02:22 UTC, tkhmy commented on src/signage/src/signage/route_handler.py
> +            in_emergency = self._autoware.information.mrm_behavior == MrmState.EMERGENCY_STOP
なるほど、２つのパターンになりますね、修正します。

2023-09-08 05:51 UTC, tkhmy commented on src/signage/src/signage/route_handler.py
> +            in_emergency = self._autoware.information.mrm_behavior == MrmState.EMERGENCY_STOP
[2be2237](https://github.com/tier4/AutowareSignage/pull/77/commits/2be2237875cbaa637be810389701ae1c3fd5c1c8) で修正しました。

2023-09-12 06:07 UTC, yabuta approved these changes
LGTM

2023-09-13 04:26 UTC, merged